function Bi = HW1_Bi
%HW1_BI
%    BI = HW1_BI

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    17-Sep-2019 19:59:53

Bi = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[5,2]);
