function Bii = HW1_Bii
%HW1_BII
%    BII = HW1_BII

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    17-Sep-2019 19:59:53

Bii = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[5,2]);
