function D = HW1_D(I_leg1,I_leg2,I_torso,L_leg1,L_leg2,L_torso,m_leg1,m_leg2,m_torso,q1,q2,q3)
%HW1_D
%    D = HW1_D(I_LEG1,I_LEG2,I_TORSO,L_LEG1,L_LEG2,L_TORSO,M_LEG1,M_LEG2,M_TORSO,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    18-Sep-2019 21:07:46

t2 = cos(q3);
t3 = sin(q3);
t4 = q1+q3;
t5 = q2+q3;
t6 = L_leg1.^2;
t7 = L_leg2.^2;
t10 = m_leg1+m_leg2+m_torso;
t8 = cos(t4);
t9 = cos(t5);
t11 = sin(t4);
t12 = sin(t5);
t13 = (m_leg1.*t6)./4.0;
t14 = (m_leg2.*t7)./4.0;
t15 = (L_torso.*m_torso.*t2)./2.0;
t16 = (L_torso.*m_torso.*t3)./2.0;
t17 = -t16;
t18 = I_leg1+t13;
t19 = I_leg2+t14;
t20 = (L_leg1.*m_leg1.*t8)./2.0;
t21 = (L_leg2.*m_leg2.*t9)./2.0;
t22 = (L_leg1.*m_leg1.*t11)./2.0;
t23 = (L_leg2.*m_leg2.*t12)./2.0;
t24 = -t22;
t25 = -t23;
t26 = t15+t20+t21;
t27 = t17+t24+t25;
D = reshape([t10,0.0,t20,t21,t26,0.0,t10,t24,t25,t27,t20,t24,t18,0.0,t18,t21,t25,0.0,t19,t19,t26,t27,t18,t19,I_torso+t18+t19+(L_torso.^2.*m_torso)./4.0],[5,5]);
