function C = HW1_C(L_leg1,L_leg2,L_torso,dq1,dq2,dq3,m_leg1,m_leg2,m_torso,q1,q2,q3)
%HW1_C
%    C = HW1_C(L_LEG1,L_LEG2,L_TORSO,DQ1,DQ2,DQ3,M_LEG1,M_LEG2,M_TORSO,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    18-Sep-2019 21:07:47

t2 = dq1+dq3;
t3 = dq2+dq3;
t4 = q1+q3;
t5 = q2+q3;
t6 = cos(t4);
t7 = cos(t5);
t8 = sin(t4);
t9 = sin(t5);
C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,L_leg1.*m_leg1.*t2.*t8.*(-1.0./2.0),L_leg1.*m_leg1.*t2.*t6.*(-1.0./2.0),0.0,0.0,0.0,L_leg2.*m_leg2.*t3.*t9.*(-1.0./2.0),L_leg2.*m_leg2.*t3.*t7.*(-1.0./2.0),0.0,0.0,0.0,-dq3.*((L_leg1.*m_leg1.*t8)./2.0+(L_leg2.*m_leg2.*t9)./2.0+(L_torso.*m_torso.*sin(q3))./2.0)-(L_leg1.*dq1.*m_leg1.*t8)./2.0-(L_leg2.*dq2.*m_leg2.*t9)./2.0,-dq3.*((L_leg1.*m_leg1.*t6)./2.0+(L_leg2.*m_leg2.*t7)./2.0+(L_torso.*m_torso.*cos(q3))./2.0)-(L_leg1.*dq1.*m_leg1.*t6)./2.0-(L_leg2.*dq2.*m_leg2.*t7)./2.0,0.0,0.0,0.0],[5,5]);
