function G = HW1_G(L_leg1,L_leg2,L_torso,g,m_leg1,m_leg2,m_torso,q1,q2,q3)
%HW1_G
%    G = HW1_G(L_LEG1,L_LEG2,L_TORSO,G,M_LEG1,M_LEG2,M_TORSO,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    18-Sep-2019 21:07:47

t2 = q1+q3;
t3 = q2+q3;
t4 = sin(t2);
t5 = sin(t3);
G = [0.0;g.*(m_leg1+m_leg2+m_torso);L_leg1.*g.*m_leg1.*t4.*(-1.0./2.0);L_leg2.*g.*m_leg2.*t5.*(-1.0./2.0);g.*(L_leg1.*m_leg1.*t4+L_leg2.*m_leg2.*t5+L_torso.*m_torso.*sin(q3)).*(-1.0./2.0)];
