function Fst_u = Fst_u_gen(in1,in2)
%FST_U_GEN
%    FST_U = FST_U_GEN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Oct-2019 13:32:34

q1 = in1(3,:);
q2 = in1(4,:);
q3 = in1(5,:);
t2 = cos(q3);
t3 = sin(q3);
t4 = q1+q3;
t5 = q2+q3;
t6 = q1.*2.0;
t7 = q2.*2.0;
t9 = -q1;
t10 = -q2;
t12 = -q3;
t8 = cos(t6);
t11 = -t7;
t13 = q1+t4;
t14 = q2+t5;
t20 = t2.*4.4e+2;
t21 = t3.*4.4e+2;
t22 = q1+t12;
t23 = q2+t12;
t15 = cos(t13);
t16 = cos(t14);
t17 = q2+t13;
t18 = sin(t13);
t19 = sin(t14);
t24 = -t20;
t25 = t6+t11;
t26 = t8.*8.0e+1;
t29 = t9+t14;
t30 = t10+t13;
t31 = t11+t13;
t27 = cos(t25);
t28 = t16.*4.0e+1;
t32 = t19.*4.0e+1;
t34 = t15.*4.8e+2;
t35 = t18.*4.8e+2;
t36 = cos(t31);
t37 = sin(t31);
t33 = -t28;
t38 = -t35;
t39 = t27.*4.0e+1;
t40 = t36.*4.0e+1;
t41 = t37.*4.0e+1;
t42 = -t41;
t43 = t26+t39-3.8e+2;
t44 = 1.0./t43;
Fst_u = reshape([-t44.*(t24+t33+t34+t40-cos(t4).*4.0e+2+cos(t22).*8.0e+1+cos(t29).*4.0e+1),-t44.*(t21+t32+t38+t42+sin(t4).*4.0e+2+sin(t22).*8.0e+1-sin(t29).*4.0e+1),-t44.*(t24+t33+t34+t40+cos(t5).*4.0e+2-cos(t17).*8.0e+1+cos(t23).*8.0e+1-cos(t30).*4.4e+2),-t44.*(t21+t32+t38+t42-sin(t5).*4.0e+2+sin(t17).*8.0e+1+sin(t23).*8.0e+1+sin(t30).*4.4e+2)],[2,2]);
