function Lfy = Lfy_gen(in1,in2,in3)
%LFY_GEN
%    LFY = LFY_GEN(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    13-Nov-2019 20:31:55

alph1 = in2(:,2);
alph2 = in2(:,3);
alph3 = in2(:,4);
beta0 = in3(:,1);
beta1 = in3(:,2);
beta2 = in3(:,3);
beta3 = in3(:,4);
dq1 = in1(8,:);
dq2 = in1(9,:);
dq3 = in1(10,:);
q1 = in1(3,:);
q3 = in1(5,:);
t2 = pi.*2.0;
t3 = q1.*2.0;
t4 = q3.*2.0;
t5 = -pi;
t7 = pi.*(7.0./8.0);
t9 = pi.*(9.0./8.0);
t6 = -t2;
t8 = -t7;
t10 = q1+q3+t5;
t11 = -t9;
t12 = t10.^2;
t13 = beta1.*t10;
t14 = q1+q3+t8;
t17 = t3+t4+t6;
t18 = q1+q3+t11;
t15 = beta2.*t12;
t16 = beta3.*t12;
t19 = alph3.*t12.*3.0;
t20 = alph2.*t17;
t21 = beta2.*t17;
t22 = beta3.*t17;
t23 = beta1+t21+t22;
t24 = beta0+t13+t15+t16;
t25 = t14.*t24;
t26 = t18.*t24;
t27 = t14.*t18.*t23;
Lfy = [-dq1.*(alph1+t19+t20)-dq3.*(alph1+t19+t20-1.0);dq2-dq1.*(t25+t26+t27-1.0)-dq3.*(t25+t26+t27-2.0)];
