function pLeg2 = pLeg2_gen(in1)
%PLEG2_GEN
%    PLEG2 = PLEG2_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    20-Oct-2019 14:02:15

q2 = in1(4,:);
q3 = in1(5,:);
x = in1(1,:);
y = in1(2,:);
t2 = pi./2.0;
t3 = -t2;
t4 = q2+q3+t3;
pLeg2 = [x+cos(t4);y-sin(t4)];
