function Bii = HW1_Bii
%HW1_BII
%    BII = HW1_BII

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    18-Sep-2019 21:07:48

Bii = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[5,2]);
