function Di = HW1_Di
%HW1_DI
%    DI = HW1_DI

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    18-Sep-2019 21:07:47

Di = reshape([2.0e+1,0.0,-2.5,-2.165063509462925,-2.5,0.0,2.0e+1,0.0,-1.25,-2.5,-2.5,0.0,1.75,0.0,1.75,-2.165063509462925,-1.25,0.0,1.75,1.75,-2.5,-2.5,1.75,1.75,5.125],[5,5]);
