function Bi = HW1_Bi
%HW1_BI
%    BI = HW1_BI

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    18-Sep-2019 21:07:47

Bi = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[5,2]);
