function B = HW1_B
%HW1_B
%    B = HW1_B

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    18-Sep-2019 21:07:47

B = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[5,2]);
